#!/usr/bin/env bash
#
# vim: noai:ts=2:sw=2
# $1: gid
# $2: the number of files
# $3: file path
# upload aria2 download to remote using rclone
set -o nounset -o errexit -o pipefail
IFS=$'\n\t'

SCRIPT_PATH="$(cd "$(dirname "$0")"; pwd)"
LOGFILE="${SCRIPT_PATH}/user_action.log"

echo "$(date '+%Y-%m-%d %H:%M:%S') $@：这是用户自定义文件" >> "${LOGFILE}"
